server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:mariadb://localhost:3306/catalog?useLegacyDatatimeCode=false&serverTimezone=UTC
    username: mysql
    password: changeme
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    user:
      name: admin
      password: admin
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl